2021-12-17 00:16:37.469 | ERROR    | main:imports:20 - mongo:27017: [Errno 11001] getaddrinfo failed, Timeout: 30s, Topology Description: <TopologyDescription id: 61bbac920fb3de180803442a, topology_type: Single, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno 11001] getaddrinfo failed')>]>
Traceback (most recent call last):

  File "E:\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
           |         |     -> {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "E:\python\Scripts\uvicorn.exe...
           |         -> <code object <module> at 0x00000257C5DBDBE0, file "E:\python\Scripts\uvicorn.exe\__main__.py", line 2>
           -> <function _run_code at 0x00000257C55BB820>

  File "E:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
         |     -> {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "E:\python\Scripts\uvicorn.exe...
         -> <code object <module> at 0x00000257C5DBDBE0, file "E:\python\Scripts\uvicorn.exe\__main__.py", line 2>

  File "E:\python\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
    sys.exit(main())
    |   |    -> <Command main>
    |   -> <built-in function exit>
    -> <module 'sys' (built-in)>

  File "E:\python\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
           |    |     |       -> {}
           |    |     -> ()
           |    -> <function BaseCommand.main at 0x00000257C7C64B80>
           -> <Command main>

  File "E:\python\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
         |    |      -> <click.core.Context object at 0x00000257C818D430>
         |    -> <function Command.invoke at 0x00000257C7C69670>
         -> <Command main>

  File "E:\python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           |   |      |    |           |   -> {'app': 'main:app', 'host': '127.0.0.1', 'port': 8000, 'uds': None, 'fd': None, 'debug': False, 'reload': False, 'reload_dirs...
           |   |      |    |           -> <click.core.Context object at 0x00000257C818D430>
           |   |      |    -> <function main at 0x00000257C8247430>
           |   |      -> <Command main>
           |   -> <function Context.invoke at 0x00000257C7C64430>
           -> <click.core.Context object at 0x00000257C818D430>

  File "E:\python\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
                       |       -> {'app': 'main:app', 'host': '127.0.0.1', 'port': 8000, 'uds': None, 'fd': None, 'debug': False, 'reload': False, 'reload_dirs...
                       -> ()

  File "E:\python\lib\site-packages\uvicorn\main.py", line 426, in main
    run(app, **kwargs)
    |   |      -> {'host': '127.0.0.1', 'port': 8000, 'uds': None, 'fd': None, 'loop': 'auto', 'http': 'auto', 'ws': 'auto', 'ws_max_size': 167...
    |   -> 'main:app'
    -> <function run at 0x00000257C81EBE50>

  File "E:\python\lib\site-packages\uvicorn\main.py", line 452, in run
    server.run()
    |      -> <function Server.run at 0x00000257C81EB790>
    -> <uvicorn.server.Server object at 0x00000257C8244D00>

  File "E:\python\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
           |       |   |    |             -> None
           |       |   |    -> <function Server.serve at 0x00000257C81EB820>
           |       |   -> <uvicorn.server.Server object at 0x00000257C8244D00>
           |       -> <function run at 0x00000257C5DC8550>
           -> <module 'asyncio' from 'E:\\python\\lib\\asyncio\\__init__.py'>

  File "E:\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           |    |                  -> <coroutine object Server.serve at 0x00000257C820CEC0>
           |    -> <function BaseEventLoop.run_until_complete at 0x00000257C79C2820>
           -> <ProactorEventLoop running=True closed=False debug=False>

  File "E:\python\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x00000257C7A85550>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "E:\python\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "E:\python\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x00000257C79C6310>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "E:\python\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x00000257C7958F70>
    -> <Handle <TaskStepMethWrapper object at 0x00000257CFA2A340>()>

  File "E:\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskStepMethWrapper object at 0x00000257CFA2A340>()>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskStepMethWrapper object at 0x00000257CFA2A340>()>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskStepMethWrapper object at 0x00000257CFA2A340>()>

  File "E:\python\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   |   |    |      |    |        |    -> <function RequestResponseCycle.send at 0x00000257C8299A60>
                   |   |    |      |    |        -> <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFA2A310>
                   |   |    |      |    -> <function RequestResponseCycle.receive at 0x00000257C8299AF0>
                   |   |    |      -> <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFA2A310>
                   |   |    -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                   |   -> <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFA2A310>
                   -> <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x00000257C825A0A0>

  File "E:\python\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
                 |    |   |      |        -> <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFA2A310>>
                 |    |   |      -> <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFA2A...
                 |    |   -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                 |    -> <fastapi.applications.FastAPI object at 0x00000257C829E280>
                 -> <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x00000257C825A0A0>

  File "E:\python\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
                           |      |        -> <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFA2A310>>
                           |      -> <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFA2A...
                           -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...

  File "E:\python\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          |    |                |      |        -> <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFA2A310>>
          |    |                |      -> <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFA2A...
          |    |                -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          |    -> <starlette.middleware.errors.ServerErrorMiddleware object at 0x00000257C8C880A0>
          -> <fastapi.applications.FastAPI object at 0x00000257C829E280>

  File "E:\python\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          |    |   |      |        -> <function ServerErrorMiddleware.__call__.<locals>._send at 0x00000257CFA05CA0>
          |    |   |      -> <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFA2A...
          |    |   -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          |    -> <starlette.exceptions.ExceptionMiddleware object at 0x00000257C8C88040>
          -> <starlette.middleware.errors.ServerErrorMiddleware object at 0x00000257C8C880A0>

  File "E:\python\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          |    |   |      |        -> <function ExceptionMiddleware.__call__.<locals>.sender at 0x00000257CFA05D30>
          |    |   |      -> <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFA2A...
          |    |   -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          |    -> <fastapi.routing.APIRouter object at 0x00000257C829E310>
          -> <starlette.exceptions.ExceptionMiddleware object at 0x00000257C8C88040>

  File "E:\python\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
          |     |      |      |        -> <function ExceptionMiddleware.__call__.<locals>.sender at 0x00000257CFA05D30>
          |     |      |      -> <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFA2A...
          |     |      -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          |     -> <function Route.handle at 0x00000257C87C6280>
          -> <fastapi.routing.APIRoute object at 0x00000257CFA042E0>

  File "E:\python\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
          |    |   |      |        -> <function ExceptionMiddleware.__call__.<locals>.sender at 0x00000257CFA05D30>
          |    |   |      -> <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFA2A...
          |    |   -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          |    -> <function request_response.<locals>.app at 0x00000257CFA05040>
          -> <fastapi.routing.APIRoute object at 0x00000257CFA042E0>

  File "E:\python\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
                     |    -> <starlette.requests.Request object at 0x00000257CFA0FE20>
                     -> <function get_request_handler.<locals>.app at 0x00000257CF9F7F70>

  File "E:\python\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
                         -> <function run_endpoint_function at 0x00000257C87B8310>

  File "E:\python\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
                 |         |      -> {'request': <starlette.requests.Request object at 0x00000257CFA0FE20>}
                 |         -> <function imports at 0x00000257CF9F7EE0>
                 -> <fastapi.dependencies.models.Dependant object at 0x00000257CFA04400>

> File "E:\study\kursach\.\main.py", line 17, in imports
    response = insert_user(await request.json())
               |                 |       -> <function Request.json at 0x00000257C875D4C0>
               |                 -> <starlette.requests.Request object at 0x00000257CFA0FE20>
               -> <function insert_user at 0x00000257C8AFA670>

  File "E:\study\kursach\.\views.py", line 13, in insert_user
    impoted_users = list(user_collection.find({}))
                         |               -> <function Collection.find at 0x00000257C8A4FC10>
                         -> Collection(Database(MongoClient(host=['mongo:27017'], document_class=dict, tz_aware=False, connect=True), 'kursach_mongo'), '...

  File "E:\python\lib\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
           |               |    -> <function Cursor._refresh at 0x00000257C8A1F790>
           |               -> <pymongo.cursor.Cursor object at 0x00000257CFA2A040>
           -> <pymongo.cursor.Cursor object at 0x00000257CFA2A040>

  File "E:\python\lib\site-packages\pymongo\cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
    |                -> <pymongo.cursor.Cursor object at 0x00000257CFA2A040>
    -> <pymongo.cursor.Cursor object at 0x00000257CFA2A040>

  File "E:\python\lib\site-packages\pymongo\mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
           -> MongoClient(host=['mongo:27017'], document_class=dict, tz_aware=False, connect=True)

  File "E:\python\lib\site-packages\pymongo\mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
                     |    -> <function MongoClient._get_server_session at 0x00000257C8AF91F0>
                     -> MongoClient(host=['mongo:27017'], document_class=dict, tz_aware=False, connect=True)

  File "E:\python\lib\site-packages\pymongo\mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
           |    |         -> <function Topology.get_server_session at 0x00000257C8AF1940>
           |    -> <Topology <TopologyDescription id: 61bbac920fb3de180803442a, topology_type: Single, servers: [<ServerDescription ('mongo', 27...
           -> MongoClient(host=['mongo:27017'], document_class=dict, tz_aware=False, connect=True)

  File "E:\python\lib\site-packages\pymongo\topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
                      |    -> <function Topology._check_session_support at 0x00000257C8AF18B0>
                      -> <Topology <TopologyDescription id: 61bbac920fb3de180803442a, topology_type: Single, servers: [<ServerDescription ('mongo', 27...

  File "E:\python\lib\site-packages\pymongo\topology.py", line 499, in _check_session_support
    self._select_servers_loop(
    |    -> <function Topology._select_servers_loop at 0x00000257C8AEFB80>
    -> <Topology <TopologyDescription id: 61bbac920fb3de180803442a, topology_type: Single, servers: [<ServerDescription ('mongo', 27...

  File "E:\python\lib\site-packages\pymongo\topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
          -> <class 'pymongo.errors.ServerSelectionTimeoutError'>

pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno 11001] getaddrinfo failed, Timeout: 30s, Topology Description: <TopologyDescription id: 61bbac920fb3de180803442a, topology_type: Single, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno 11001] getaddrinfo failed')>]>
2021-12-17 00:17:08.008 | ERROR    | main:get_imports:30 - mongo:27017: [Errno 11001] getaddrinfo failed, Timeout: 30s, Topology Description: <TopologyDescription id: 61bbac920fb3de180803442a, topology_type: Single, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno 11001] getaddrinfo failed')>]>
Traceback (most recent call last):

  File "E:\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
           |         |     -> {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "E:\python\Scripts\uvicorn.exe...
           |         -> <code object <module> at 0x00000257C5DBDBE0, file "E:\python\Scripts\uvicorn.exe\__main__.py", line 2>
           -> <function _run_code at 0x00000257C55BB820>

  File "E:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
         |     -> {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "E:\python\Scripts\uvicorn.exe...
         -> <code object <module> at 0x00000257C5DBDBE0, file "E:\python\Scripts\uvicorn.exe\__main__.py", line 2>

  File "E:\python\Scripts\uvicorn.exe\__main__.py", line 7, in <module>
    sys.exit(main())
    |   |    -> <Command main>
    |   -> <built-in function exit>
    -> <module 'sys' (built-in)>

  File "E:\python\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
           |    |     |       -> {}
           |    |     -> ()
           |    -> <function BaseCommand.main at 0x00000257C7C64B80>
           -> <Command main>

  File "E:\python\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
         |    |      -> <click.core.Context object at 0x00000257C818D430>
         |    -> <function Command.invoke at 0x00000257C7C69670>
         -> <Command main>

  File "E:\python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           |   |      |    |           |   -> {'app': 'main:app', 'host': '127.0.0.1', 'port': 8000, 'uds': None, 'fd': None, 'debug': False, 'reload': False, 'reload_dirs...
           |   |      |    |           -> <click.core.Context object at 0x00000257C818D430>
           |   |      |    -> <function main at 0x00000257C8247430>
           |   |      -> <Command main>
           |   -> <function Context.invoke at 0x00000257C7C64430>
           -> <click.core.Context object at 0x00000257C818D430>

  File "E:\python\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
                       |       -> {'app': 'main:app', 'host': '127.0.0.1', 'port': 8000, 'uds': None, 'fd': None, 'debug': False, 'reload': False, 'reload_dirs...
                       -> ()

  File "E:\python\lib\site-packages\uvicorn\main.py", line 426, in main
    run(app, **kwargs)
    |   |      -> {'host': '127.0.0.1', 'port': 8000, 'uds': None, 'fd': None, 'loop': 'auto', 'http': 'auto', 'ws': 'auto', 'ws_max_size': 167...
    |   -> 'main:app'
    -> <function run at 0x00000257C81EBE50>

  File "E:\python\lib\site-packages\uvicorn\main.py", line 452, in run
    server.run()
    |      -> <function Server.run at 0x00000257C81EB790>
    -> <uvicorn.server.Server object at 0x00000257C8244D00>

  File "E:\python\lib\site-packages\uvicorn\server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
           |       |   |    |             -> None
           |       |   |    -> <function Server.serve at 0x00000257C81EB820>
           |       |   -> <uvicorn.server.Server object at 0x00000257C8244D00>
           |       -> <function run at 0x00000257C5DC8550>
           -> <module 'asyncio' from 'E:\\python\\lib\\asyncio\\__init__.py'>

  File "E:\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
           |    |                  -> <coroutine object Server.serve at 0x00000257C820CEC0>
           |    -> <function BaseEventLoop.run_until_complete at 0x00000257C79C2820>
           -> <ProactorEventLoop running=True closed=False debug=False>

  File "E:\python\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
    |    -> <function ProactorEventLoop.run_forever at 0x00000257C7A85550>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "E:\python\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "E:\python\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    |    -> <function BaseEventLoop._run_once at 0x00000257C79C6310>
    -> <ProactorEventLoop running=True closed=False debug=False>

  File "E:\python\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    |      -> <function Handle._run at 0x00000257C7958F70>
    -> <Handle <TaskStepMethWrapper object at 0x00000257CFB02250>()>

  File "E:\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    |    |            |    |           |    -> <member '_args' of 'Handle' objects>
    |    |            |    |           -> <Handle <TaskStepMethWrapper object at 0x00000257CFB02250>()>
    |    |            |    -> <member '_callback' of 'Handle' objects>
    |    |            -> <Handle <TaskStepMethWrapper object at 0x00000257CFB02250>()>
    |    -> <member '_context' of 'Handle' objects>
    -> <Handle <TaskStepMethWrapper object at 0x00000257CFB02250>()>

  File "E:\python\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
                   |   |    |      |    |        |    -> <function RequestResponseCycle.send at 0x00000257C8299A60>
                   |   |    |      |    |        -> <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFB02220>
                   |   |    |      |    -> <function RequestResponseCycle.receive at 0x00000257C8299AF0>
                   |   |    |      -> <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFB02220>
                   |   |    -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                   |   -> <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFB02220>
                   -> <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x00000257C825A0A0>

  File "E:\python\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
                 |    |   |      |        -> <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFB02220>>
                 |    |   |      -> <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFB02...
                 |    |   -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
                 |    -> <fastapi.applications.FastAPI object at 0x00000257C829E280>
                 -> <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x00000257C825A0A0>

  File "E:\python\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
                           |      |        -> <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFB02220>>
                           |      -> <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFB02...
                           -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...

  File "E:\python\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
          |    |                |      |        -> <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFB02220>>
          |    |                |      -> <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFB02...
          |    |                -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          |    -> <starlette.middleware.errors.ServerErrorMiddleware object at 0x00000257C8C880A0>
          -> <fastapi.applications.FastAPI object at 0x00000257C829E280>

  File "E:\python\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
          |    |   |      |        -> <function ServerErrorMiddleware.__call__.<locals>._send at 0x00000257CFA05DC0>
          |    |   |      -> <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFB02...
          |    |   -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          |    -> <starlette.exceptions.ExceptionMiddleware object at 0x00000257C8C88040>
          -> <starlette.middleware.errors.ServerErrorMiddleware object at 0x00000257C8C880A0>

  File "E:\python\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
          |    |   |      |        -> <function ExceptionMiddleware.__call__.<locals>.sender at 0x00000257CFABB5E0>
          |    |   |      -> <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFB02...
          |    |   -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          |    -> <fastapi.routing.APIRouter object at 0x00000257C829E310>
          -> <starlette.exceptions.ExceptionMiddleware object at 0x00000257C8C88040>

  File "E:\python\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
          |     |      |      |        -> <function ExceptionMiddleware.__call__.<locals>.sender at 0x00000257CFABB5E0>
          |     |      |      -> <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFB02...
          |     |      -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          |     -> <function Route.handle at 0x00000257C87C6280>
          -> <fastapi.routing.APIRoute object at 0x00000257CFA04640>

  File "E:\python\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
          |    |   |      |        -> <function ExceptionMiddleware.__call__.<locals>.sender at 0x00000257CFABB5E0>
          |    |   |      -> <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x00000257CFB02...
          |    |   -> {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'server': ('127.0.0.1', 8000), 'cl...
          |    -> <function request_response.<locals>.app at 0x00000257CFA051F0>
          -> <fastapi.routing.APIRoute object at 0x00000257CFA04640>

  File "E:\python\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
                     |    -> <starlette.requests.Request object at 0x00000257CFAF7F70>
                     -> <function get_request_handler.<locals>.app at 0x00000257CFA05160>

  File "E:\python\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
                         -> <function run_endpoint_function at 0x00000257C87B8310>

  File "E:\python\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
                 |         |      -> {'import_id': 3}
                 |         -> <function get_imports at 0x00000257CFA050D0>
                 -> <fastapi.dependencies.models.Dependant object at 0x00000257CFA04730>

> File "E:\study\kursach\.\main.py", line 27, in get_imports
    result = get_imports_db(import_id)
             |              -> 3
             -> <function get_imports_db at 0x00000257CF9F7790>

  File "E:\study\kursach\.\views.py", line 38, in get_imports_db
    users = list(user_collection.find({'import_id': import_id}))
                 |               |                  -> 3
                 |               -> <function Collection.find at 0x00000257C8A4FC10>
                 -> Collection(Database(MongoClient(host=['mongo:27017'], document_class=dict, tz_aware=False, connect=True), 'kursach_mongo'), '...

  File "E:\python\lib\site-packages\pymongo\cursor.py", line 1238, in next
    if len(self.__data) or self._refresh():
           |               |    -> <function Cursor._refresh at 0x00000257C8A1F790>
           |               -> <pymongo.cursor.Cursor object at 0x00000257CFB021F0>
           -> <pymongo.cursor.Cursor object at 0x00000257CFB021F0>

  File "E:\python\lib\site-packages\pymongo\cursor.py", line 1130, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
    |                -> <pymongo.cursor.Cursor object at 0x00000257CFB021F0>
    -> <pymongo.cursor.Cursor object at 0x00000257CFB021F0>

  File "E:\python\lib\site-packages\pymongo\mongo_client.py", line 1935, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
           -> MongoClient(host=['mongo:27017'], document_class=dict, tz_aware=False, connect=True)

  File "E:\python\lib\site-packages\pymongo\mongo_client.py", line 1883, in __start_session
    server_session = self._get_server_session()
                     |    -> <function MongoClient._get_server_session at 0x00000257C8AF91F0>
                     -> MongoClient(host=['mongo:27017'], document_class=dict, tz_aware=False, connect=True)

  File "E:\python\lib\site-packages\pymongo\mongo_client.py", line 1921, in _get_server_session
    return self._topology.get_server_session()
           |    |         -> <function Topology.get_server_session at 0x00000257C8AF1940>
           |    -> <Topology <TopologyDescription id: 61bbac920fb3de180803442a, topology_type: Single, servers: [<ServerDescription ('mongo', 27...
           -> MongoClient(host=['mongo:27017'], document_class=dict, tz_aware=False, connect=True)

  File "E:\python\lib\site-packages\pymongo\topology.py", line 520, in get_server_session
    session_timeout = self._check_session_support()
                      |    -> <function Topology._check_session_support at 0x00000257C8AF18B0>
                      -> <Topology <TopologyDescription id: 61bbac920fb3de180803442a, topology_type: Single, servers: [<ServerDescription ('mongo', 27...

  File "E:\python\lib\site-packages\pymongo\topology.py", line 499, in _check_session_support
    self._select_servers_loop(
    |    -> <function Topology._select_servers_loop at 0x00000257C8AEFB80>
    -> <Topology <TopologyDescription id: 61bbac920fb3de180803442a, topology_type: Single, servers: [<ServerDescription ('mongo', 27...

  File "E:\python\lib\site-packages\pymongo\topology.py", line 218, in _select_servers_loop
    raise ServerSelectionTimeoutError(
          -> <class 'pymongo.errors.ServerSelectionTimeoutError'>

pymongo.errors.ServerSelectionTimeoutError: mongo:27017: [Errno 11001] getaddrinfo failed, Timeout: 30s, Topology Description: <TopologyDescription id: 61bbac920fb3de180803442a, topology_type: Single, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno 11001] getaddrinfo failed')>]>
